### PR TITLE
Test Travis

### PR DESCRIPTION
**Pull request by Gregoirevda**

### CODE REVIEW

**Comment by Gregoirevda** [comment]
@grsabreu You know what's going on here?

**Comment by fakenickels** [comment]
Hmm pretty weird, this is all the setup I needed for Travis https://github.com/Astrocoders/reform/blob/master/.travis.yml

**Comment by fakenickels** [comment]
I don't think it's necessary to install bs-platform globally

**Comment by Gregoirevda** [comment]
Ah it passed. Seems to be related to yarn. Thanks for the ref

**Comment by fakenickels** [comment]
Nice

**Comment by Gregoirevda** [comment]
Takes 2 to 3 minutes, would be good to improve that. OCaml image or caching...

**Pull request merged**
